cand.set[[1]] <- lmer(prey ~ predator.lag04 * environment.lag00 + (predator.lag04 + environment.lag00 | region), data = d.scaled, REML = FALSE)
cand.set[[2]] <- lmer(prey ~ predator.lag04 * environment.lag01 + (predator.lag04 + environment.lag01 | region), data = d.scaled, REML = FALSE)
cand.set[[3]] <- lmer(prey ~ predator.lag04 * environment.lag02 + (predator.lag04 + environment.lag02 | region), data = d.scaled, REML = FALSE)
cand.set[[4]] <- lmer(prey ~ predator.lag04 * environment.lag03 + (predator.lag04 + environment.lag03 | region), data = d.scaled, REML = FALSE)
cand.set[[5]] <- lmer(prey ~ predator.lag04 * environment.lag04 + (predator.lag04 + environment.lag04 | region), data = d.scaled, REML = FALSE)
cand.set[[6]] <- lmer(prey ~ predator.lag04 * environment.lag05 + (predator.lag04 + environment.lag05 | region), data = d.scaled, REML = FALSE)
cand.set[[7]] <- lmer(prey ~ predator.lag04 * environment.lag06 + (predator.lag04 + environment.lag06 | region), data = d.scaled, REML = FALSE)
cand.set[[8]] <- lmer(prey ~ predator.lag04 * environment.lag07 + (predator.lag04 + environment.lag07 | region), data = d.scaled, REML = FALSE)
cand.set[[9]] <- lmer(prey ~ predator.lag04 * environment.lag08 + (predator.lag04 + environment.lag08 | region), data = d.scaled, REML = FALSE)
cand.set[[10]] <- lmer(prey ~ predator.lag04 * environment.lag09 + (predator.lag04 + environment.lag09 | region), data = d.scaled, REML = FALSE)
cand.set[[11]] <- lmer(prey ~ predator.lag04 * environment.lag10 + (predator.lag04 + environment.lag10 | region), data = d.scaled, REML = FALSE)
cand.set[[12]] <- lmer(prey ~ predator.lag05 * environment.lag00 + (predator.lag05 + environment.lag00 | region), data = d.scaled, REML = FALSE)
cand.set[[13]] <- lmer(prey ~ predator.lag05 * environment.lag01 + (predator.lag05 + environment.lag01 | region), data = d.scaled, REML = FALSE)
cand.set[[14]] <- lmer(prey ~ predator.lag05 * environment.lag02 + (predator.lag05 + environment.lag02 | region), data = d.scaled, REML = FALSE)
cand.set[[15]] <- lmer(prey ~ predator.lag05 * environment.lag03 + (predator.lag05 + environment.lag03 | region), data = d.scaled, REML = FALSE)
cand.set[[16]] <- lmer(prey ~ predator.lag05 * environment.lag04 + (predator.lag05 + environment.lag04 | region), data = d.scaled, REML = FALSE)
cand.set[[17]] <- lmer(prey ~ predator.lag05 * environment.lag05 + (predator.lag05 + environment.lag05 | region), data = d.scaled, REML = FALSE)
cand.set[[18]] <- lmer(prey ~ predator.lag05 * environment.lag06 + (predator.lag05 + environment.lag06 | region), data = d.scaled, REML = FALSE)
cand.set[[19]] <- lmer(prey ~ predator.lag05 * environment.lag07 + (predator.lag05 + environment.lag07 | region), data = d.scaled, REML = FALSE)
cand.set[[20]] <- lmer(prey ~ predator.lag05 * environment.lag08 + (predator.lag05 + environment.lag08 | region), data = d.scaled, REML = FALSE)
cand.set[[21]] <- lmer(prey ~ predator.lag05 * environment.lag09 + (predator.lag05 + environment.lag09 | region), data = d.scaled, REML = FALSE)
cand.set[[22]] <- lmer(prey ~ predator.lag05 * environment.lag10 + (predator.lag05 + environment.lag10 | region), data = d.scaled, REML = FALSE)
cand.set[[23]] <- lmer(prey ~ predator.lag06 * environment.lag00 + (predator.lag06 + environment.lag00 | region), data = d.scaled, REML = FALSE)
cand.set[[24]] <- lmer(prey ~ predator.lag06 * environment.lag01 + (predator.lag06 + environment.lag01 | region), data = d.scaled, REML = FALSE)
cand.set[[25]] <- lmer(prey ~ predator.lag06 * environment.lag02 + (predator.lag06 + environment.lag02 | region), data = d.scaled, REML = FALSE)
cand.set[[26]] <- lmer(prey ~ predator.lag06 * environment.lag03 + (predator.lag06 + environment.lag03 | region), data = d.scaled, REML = FALSE)
cand.set[[27]] <- lmer(prey ~ predator.lag06 * environment.lag04 + (predator.lag06 + environment.lag04 | region), data = d.scaled, REML = FALSE)
cand.set[[28]] <- lmer(prey ~ predator.lag06 * environment.lag05 + (predator.lag06 + environment.lag05 | region), data = d.scaled, REML = FALSE)
cand.set[[29]] <- lmer(prey ~ predator.lag06 * environment.lag06 + (predator.lag06 + environment.lag06 | region), data = d.scaled, REML = FALSE)
cand.set[[30]] <- lmer(prey ~ predator.lag06 * environment.lag07 + (predator.lag06 + environment.lag07 | region), data = d.scaled, REML = FALSE)
cand.set[[31]] <- lmer(prey ~ predator.lag06 * environment.lag08 + (predator.lag06 + environment.lag08 | region), data = d.scaled, REML = FALSE)
cand.set[[32]] <- lmer(prey ~ predator.lag06 * environment.lag09 + (predator.lag06 + environment.lag09 | region), data = d.scaled, REML = FALSE)
cand.set[[33]] <- lmer(prey ~ predator.lag06 * environment.lag10 + (predator.lag06 + environment.lag10 | region), data = d.scaled, REML = FALSE)
cand.set[[34]] <- lmer(prey ~ predator.lag07 * environment.lag00 + (predator.lag07 + environment.lag00 | region), data = d.scaled, REML = FALSE)
cand.set[[35]] <- lmer(prey ~ predator.lag07 * environment.lag01 + (predator.lag07 + environment.lag01 | region), data = d.scaled, REML = FALSE)
cand.set[[36]] <- lmer(prey ~ predator.lag07 * environment.lag02 + (predator.lag07 + environment.lag02 | region), data = d.scaled, REML = FALSE)
cand.set[[37]] <- lmer(prey ~ predator.lag07 * environment.lag03 + (predator.lag07 + environment.lag03 | region), data = d.scaled, REML = FALSE)
cand.set[[38]] <- lmer(prey ~ predator.lag07 * environment.lag04 + (predator.lag07 + environment.lag04 | region), data = d.scaled, REML = FALSE)
cand.set[[39]] <- lmer(prey ~ predator.lag07 * environment.lag05 + (predator.lag07 + environment.lag05 | region), data = d.scaled, REML = FALSE)
cand.set[[40]] <- lmer(prey ~ predator.lag07 * environment.lag06 + (predator.lag07 + environment.lag06 | region), data = d.scaled, REML = FALSE)
cand.set[[41]] <- lmer(prey ~ predator.lag07 * environment.lag07 + (predator.lag07 + environment.lag07 | region), data = d.scaled, REML = FALSE)
cand.set[[42]] <- lmer(prey ~ predator.lag07 * environment.lag08 + (predator.lag07 + environment.lag08 | region), data = d.scaled, REML = FALSE)
cand.set[[43]] <- lmer(prey ~ predator.lag07 * environment.lag09 + (predator.lag07 + environment.lag09 | region), data = d.scaled, REML = FALSE)
cand.set[[44]] <- lmer(prey ~ predator.lag07 * environment.lag10 + (predator.lag07 + environment.lag10 | region), data = d.scaled, REML = FALSE)
cand.set[[45]] <- lmer(prey ~ predator.lag08 * environment.lag00 + (predator.lag08 + environment.lag00 | region), data = d.scaled, REML = FALSE)
cand.set[[46]] <- lmer(prey ~ predator.lag08 * environment.lag01 + (predator.lag08 + environment.lag01 | region), data = d.scaled, REML = FALSE)
cand.set[[47]] <- lmer(prey ~ predator.lag08 * environment.lag02 + (predator.lag08 + environment.lag02 | region), data = d.scaled, REML = FALSE)
cand.set[[48]] <- lmer(prey ~ predator.lag08 * environment.lag03 + (predator.lag08 + environment.lag03 | region), data = d.scaled, REML = FALSE)
cand.set[[49]] <- lmer(prey ~ predator.lag08 * environment.lag04 + (predator.lag08 + environment.lag04 | region), data = d.scaled, REML = FALSE)
cand.set[[50]] <- lmer(prey ~ predator.lag08 * environment.lag05 + (predator.lag08 + environment.lag05 | region), data = d.scaled, REML = FALSE)
cand.set[[51]] <- lmer(prey ~ predator.lag08 * environment.lag06 + (predator.lag08 + environment.lag06 | region), data = d.scaled, REML = FALSE)
cand.set[[52]] <- lmer(prey ~ predator.lag08 * environment.lag07 + (predator.lag08 + environment.lag07 | region), data = d.scaled, REML = FALSE)
cand.set[[53]] <- lmer(prey ~ predator.lag08 * environment.lag08 + (predator.lag08 + environment.lag08 | region), data = d.scaled, REML = FALSE)
cand.set[[54]] <- lmer(prey ~ predator.lag08 * environment.lag09 + (predator.lag08 + environment.lag09 | region), data = d.scaled, REML = FALSE)
cand.set[[55]] <- lmer(prey ~ predator.lag08 * environment.lag10 + (predator.lag08 + environment.lag10 | region), data = d.scaled, REML = FALSE)
cand.set[[56]] <- lmer(prey ~ predator.lag09 * environment.lag00 + (predator.lag09 + environment.lag00 | region), data = d.scaled, REML = FALSE)
cand.set[[57]] <- lmer(prey ~ predator.lag09 * environment.lag01 + (predator.lag09 + environment.lag01 | region), data = d.scaled, REML = FALSE)
cand.set[[58]] <- lmer(prey ~ predator.lag09 * environment.lag02 + (predator.lag09 + environment.lag02 | region), data = d.scaled, REML = FALSE)
cand.set[[59]] <- lmer(prey ~ predator.lag09 * environment.lag03 + (predator.lag09 + environment.lag03 | region), data = d.scaled, REML = FALSE)
cand.set[[60]] <- lmer(prey ~ predator.lag09 * environment.lag04 + (predator.lag09 + environment.lag04 | region), data = d.scaled, REML = FALSE)
cand.set[[61]] <- lmer(prey ~ predator.lag09 * environment.lag05 + (predator.lag09 + environment.lag05 | region), data = d.scaled, REML = FALSE)
cand.set[[62]] <- lmer(prey ~ predator.lag09 * environment.lag06 + (predator.lag09 + environment.lag06 | region), data = d.scaled, REML = FALSE)
cand.set[[63]] <- lmer(prey ~ predator.lag09 * environment.lag07 + (predator.lag09 + environment.lag07 | region), data = d.scaled, REML = FALSE)
cand.set[[64]] <- lmer(prey ~ predator.lag09 * environment.lag08 + (predator.lag09 + environment.lag08 | region), data = d.scaled, REML = FALSE)
cand.set[[65]] <- lmer(prey ~ predator.lag09 * environment.lag09 + (predator.lag09 + environment.lag09 | region), data = d.scaled, REML = FALSE)
cand.set[[66]] <- lmer(prey ~ predator.lag09 * environment.lag10 + (predator.lag09 + environment.lag10 | region), data = d.scaled, REML = FALSE)
cand.set[[67]] <- lmer(prey ~ predator.lag10 * environment.lag00 + (predator.lag10 + environment.lag00 | region), data = d.scaled, REML = FALSE)
cand.set[[68]] <- lmer(prey ~ predator.lag10 * environment.lag01 + (predator.lag10 + environment.lag01 | region), data = d.scaled, REML = FALSE)
cand.set[[69]] <- lmer(prey ~ predator.lag10 * environment.lag02 + (predator.lag10 + environment.lag02 | region), data = d.scaled, REML = FALSE)
cand.set[[70]] <- lmer(prey ~ predator.lag10 * environment.lag03 + (predator.lag10 + environment.lag03 | region), data = d.scaled, REML = FALSE)
cand.set[[71]] <- lmer(prey ~ predator.lag10 * environment.lag04 + (predator.lag10 + environment.lag04 | region), data = d.scaled, REML = FALSE)
cand.set[[72]] <- lmer(prey ~ predator.lag10 * environment.lag05 + (predator.lag10 + environment.lag05 | region), data = d.scaled, REML = FALSE)
cand.set[[73]] <- lmer(prey ~ predator.lag10 * environment.lag06 + (predator.lag10 + environment.lag06 | region), data = d.scaled, REML = FALSE)
cand.set[[74]] <- lmer(prey ~ predator.lag10 * environment.lag07 + (predator.lag10 + environment.lag07 | region), data = d.scaled, REML = FALSE)
cand.set[[75]] <- lmer(prey ~ predator.lag10 * environment.lag08 + (predator.lag10 + environment.lag08 | region), data = d.scaled, REML = FALSE)
cand.set[[76]] <- lmer(prey ~ predator.lag10 * environment.lag09 + (predator.lag10 + environment.lag09 | region), data = d.scaled, REML = FALSE)
cand.set[[77]] <- lmer(prey ~ predator.lag10 * environment.lag10 + (predator.lag10 + environment.lag10 | region), data = d.scaled, REML = FALSE)
cand.set[[78]] <- lmer(prey ~ predator.lag04 + environment.lag00 + (predator.lag04 + environment.lag00 | region), data = d.scaled, REML = FALSE)
cand.set[[79]] <- lmer(prey ~ predator.lag04 + environment.lag01 + (predator.lag04 + environment.lag01 | region), data = d.scaled, REML = FALSE)
cand.set[[80]] <- lmer(prey ~ predator.lag04 + environment.lag02 + (predator.lag04 + environment.lag02 | region), data = d.scaled, REML = FALSE)
cand.set[[81]] <- lmer(prey ~ predator.lag04 + environment.lag03 + (predator.lag04 + environment.lag03 | region), data = d.scaled, REML = FALSE)
cand.set[[82]] <- lmer(prey ~ predator.lag04 + environment.lag04 + (predator.lag04 + environment.lag04 | region), data = d.scaled, REML = FALSE)
cand.set[[83]] <- lmer(prey ~ predator.lag04 + environment.lag05 + (predator.lag04 + environment.lag05 | region), data = d.scaled, REML = FALSE)
cand.set[[84]] <- lmer(prey ~ predator.lag04 + environment.lag06 + (predator.lag04 + environment.lag06 | region), data = d.scaled, REML = FALSE)
cand.set[[85]] <- lmer(prey ~ predator.lag04 + environment.lag07 + (predator.lag04 + environment.lag07 | region), data = d.scaled, REML = FALSE)
cand.set[[86]] <- lmer(prey ~ predator.lag04 + environment.lag08 + (predator.lag04 + environment.lag08 | region), data = d.scaled, REML = FALSE)
cand.set[[87]] <- lmer(prey ~ predator.lag04 + environment.lag09 + (predator.lag04 + environment.lag09 | region), data = d.scaled, REML = FALSE)
cand.set[[88]] <- lmer(prey ~ predator.lag04 + environment.lag10 + (predator.lag04 + environment.lag10 | region), data = d.scaled, REML = FALSE)
cand.set[[89]] <- lmer(prey ~ predator.lag05 + environment.lag00 + (predator.lag05 + environment.lag00 | region), data = d.scaled, REML = FALSE)
cand.set[[90]] <- lmer(prey ~ predator.lag05 + environment.lag01 + (predator.lag05 + environment.lag01 | region), data = d.scaled, REML = FALSE)
cand.set[[91]] <- lmer(prey ~ predator.lag05 + environment.lag02 + (predator.lag05 + environment.lag02 | region), data = d.scaled, REML = FALSE)
cand.set[[92]] <- lmer(prey ~ predator.lag05 + environment.lag03 + (predator.lag05 + environment.lag03 | region), data = d.scaled, REML = FALSE)
cand.set[[93]] <- lmer(prey ~ predator.lag05 + environment.lag04 + (predator.lag05 + environment.lag04 | region), data = d.scaled, REML = FALSE)
cand.set[[94]] <- lmer(prey ~ predator.lag05 + environment.lag05 + (predator.lag05 + environment.lag05 | region), data = d.scaled, REML = FALSE)
cand.set[[95]] <- lmer(prey ~ predator.lag05 + environment.lag06 + (predator.lag05 + environment.lag06 | region), data = d.scaled, REML = FALSE)
cand.set[[96]] <- lmer(prey ~ predator.lag05 + environment.lag07 + (predator.lag05 + environment.lag07 | region), data = d.scaled, REML = FALSE)
cand.set[[97]] <- lmer(prey ~ predator.lag05 + environment.lag08 + (predator.lag05 + environment.lag08 | region), data = d.scaled, REML = FALSE)
cand.set[[98]] <- lmer(prey ~ predator.lag05 + environment.lag09 + (predator.lag05 + environment.lag09 | region), data = d.scaled, REML = FALSE)
cand.set[[99]] <- lmer(prey ~ predator.lag05 + environment.lag10 + (predator.lag05 + environment.lag10 | region), data = d.scaled, REML = FALSE)
cand.set[[100]] <- lmer(prey ~ predator.lag06 + environment.lag00 + (predator.lag06 + environment.lag00 | region), data = d.scaled, REML = FALSE)
cand.set[[101]] <- lmer(prey ~ predator.lag06 + environment.lag01 + (predator.lag06 + environment.lag01 | region), data = d.scaled, REML = FALSE)
cand.set[[102]] <- lmer(prey ~ predator.lag06 + environment.lag02 + (predator.lag06 + environment.lag02 | region), data = d.scaled, REML = FALSE)
cand.set[[103]] <- lmer(prey ~ predator.lag06 + environment.lag03 + (predator.lag06 + environment.lag03 | region), data = d.scaled, REML = FALSE)
cand.set[[104]] <- lmer(prey ~ predator.lag06 + environment.lag04 + (predator.lag06 + environment.lag04 | region), data = d.scaled, REML = FALSE)
cand.set[[105]] <- lmer(prey ~ predator.lag06 + environment.lag05 + (predator.lag06 + environment.lag05 | region), data = d.scaled, REML = FALSE)
cand.set[[106]] <- lmer(prey ~ predator.lag06 + environment.lag06 + (predator.lag06 + environment.lag06 | region), data = d.scaled, REML = FALSE)
cand.set[[107]] <- lmer(prey ~ predator.lag06 + environment.lag07 + (predator.lag06 + environment.lag07 | region), data = d.scaled, REML = FALSE)
cand.set[[108]] <- lmer(prey ~ predator.lag06 + environment.lag08 + (predator.lag06 + environment.lag08 | region), data = d.scaled, REML = FALSE)
cand.set[[109]] <- lmer(prey ~ predator.lag06 + environment.lag09 + (predator.lag06 + environment.lag09 | region), data = d.scaled, REML = FALSE)
cand.set[[110]] <- lmer(prey ~ predator.lag06 + environment.lag10 + (predator.lag06 + environment.lag10 | region), data = d.scaled, REML = FALSE)
cand.set[[111]] <- lmer(prey ~ predator.lag07 + environment.lag00 + (predator.lag07 + environment.lag00 | region), data = d.scaled, REML = FALSE)
cand.set[[112]] <- lmer(prey ~ predator.lag07 + environment.lag01 + (predator.lag07 + environment.lag01 | region), data = d.scaled, REML = FALSE)
cand.set[[113]] <- lmer(prey ~ predator.lag07 + environment.lag02 + (predator.lag07 + environment.lag02 | region), data = d.scaled, REML = FALSE)
cand.set[[114]] <- lmer(prey ~ predator.lag07 + environment.lag03 + (predator.lag07 + environment.lag03 | region), data = d.scaled, REML = FALSE)
cand.set[[115]] <- lmer(prey ~ predator.lag07 + environment.lag04 + (predator.lag07 + environment.lag04 | region), data = d.scaled, REML = FALSE)
cand.set[[116]] <- lmer(prey ~ predator.lag07 + environment.lag05 + (predator.lag07 + environment.lag05 | region), data = d.scaled, REML = FALSE)
cand.set[[117]] <- lmer(prey ~ predator.lag07 + environment.lag06 + (predator.lag07 + environment.lag06 | region), data = d.scaled, REML = FALSE)
cand.set[[118]] <- lmer(prey ~ predator.lag07 + environment.lag07 + (predator.lag07 + environment.lag07 | region), data = d.scaled, REML = FALSE)
cand.set[[119]] <- lmer(prey ~ predator.lag07 + environment.lag08 + (predator.lag07 + environment.lag08 | region), data = d.scaled, REML = FALSE)
cand.set[[120]] <- lmer(prey ~ predator.lag07 + environment.lag09 + (predator.lag07 + environment.lag09 | region), data = d.scaled, REML = FALSE)
cand.set[[121]] <- lmer(prey ~ predator.lag07 + environment.lag10 + (predator.lag07 + environment.lag10 | region), data = d.scaled, REML = FALSE)
cand.set[[122]] <- lmer(prey ~ predator.lag08 + environment.lag00 + (predator.lag08 + environment.lag00 | region), data = d.scaled, REML = FALSE)
cand.set[[123]] <- lmer(prey ~ predator.lag08 + environment.lag01 + (predator.lag08 + environment.lag01 | region), data = d.scaled, REML = FALSE)
cand.set[[124]] <- lmer(prey ~ predator.lag08 + environment.lag02 + (predator.lag08 + environment.lag02 | region), data = d.scaled, REML = FALSE)
cand.set[[125]] <- lmer(prey ~ predator.lag08 + environment.lag03 + (predator.lag08 + environment.lag03 | region), data = d.scaled, REML = FALSE)
cand.set[[126]] <- lmer(prey ~ predator.lag08 + environment.lag04 + (predator.lag08 + environment.lag04 | region), data = d.scaled, REML = FALSE)
cand.set[[127]] <- lmer(prey ~ predator.lag08 + environment.lag05 + (predator.lag08 + environment.lag05 | region), data = d.scaled, REML = FALSE)
cand.set[[128]] <- lmer(prey ~ predator.lag08 + environment.lag06 + (predator.lag08 + environment.lag06 | region), data = d.scaled, REML = FALSE)
cand.set[[129]] <- lmer(prey ~ predator.lag08 + environment.lag07 + (predator.lag08 + environment.lag07 | region), data = d.scaled, REML = FALSE)
cand.set[[130]] <- lmer(prey ~ predator.lag08 + environment.lag08 + (predator.lag08 + environment.lag08 | region), data = d.scaled, REML = FALSE)
cand.set[[131]] <- lmer(prey ~ predator.lag08 + environment.lag09 + (predator.lag08 + environment.lag09 | region), data = d.scaled, REML = FALSE)
cand.set[[132]] <- lmer(prey ~ predator.lag08 + environment.lag10 + (predator.lag08 + environment.lag10 | region), data = d.scaled, REML = FALSE)
cand.set[[133]] <- lmer(prey ~ predator.lag09 + environment.lag00 + (predator.lag09 + environment.lag00 | region), data = d.scaled, REML = FALSE)
cand.set[[134]] <- lmer(prey ~ predator.lag09 + environment.lag01 + (predator.lag09 + environment.lag01 | region), data = d.scaled, REML = FALSE)
cand.set[[135]] <- lmer(prey ~ predator.lag09 + environment.lag02 + (predator.lag09 + environment.lag02 | region), data = d.scaled, REML = FALSE)
cand.set[[136]] <- lmer(prey ~ predator.lag09 + environment.lag03 + (predator.lag09 + environment.lag03 | region), data = d.scaled, REML = FALSE)
cand.set[[137]] <- lmer(prey ~ predator.lag09 + environment.lag04 + (predator.lag09 + environment.lag04 | region), data = d.scaled, REML = FALSE)
cand.set[[138]] <- lmer(prey ~ predator.lag09 + environment.lag05 + (predator.lag09 + environment.lag05 | region), data = d.scaled, REML = FALSE)
cand.set[[139]] <- lmer(prey ~ predator.lag09 + environment.lag06 + (predator.lag09 + environment.lag06 | region), data = d.scaled, REML = FALSE)
cand.set[[140]] <- lmer(prey ~ predator.lag09 + environment.lag07 + (predator.lag09 + environment.lag07 | region), data = d.scaled, REML = FALSE)
cand.set[[141]] <- lmer(prey ~ predator.lag09 + environment.lag08 + (predator.lag09 + environment.lag08 | region), data = d.scaled, REML = FALSE)
cand.set[[142]] <- lmer(prey ~ predator.lag09 + environment.lag09 + (predator.lag09 + environment.lag09 | region), data = d.scaled, REML = FALSE)
cand.set[[143]] <- lmer(prey ~ predator.lag09 + environment.lag10 + (predator.lag09 + environment.lag10 | region), data = d.scaled, REML = FALSE)
cand.set[[144]] <- lmer(prey ~ predator.lag10 + environment.lag00 + (predator.lag10 + environment.lag00 | region), data = d.scaled, REML = FALSE)
cand.set[[145]] <- lmer(prey ~ predator.lag10 + environment.lag01 + (predator.lag10 + environment.lag01 | region), data = d.scaled, REML = FALSE)
cand.set[[146]] <- lmer(prey ~ predator.lag10 + environment.lag02 + (predator.lag10 + environment.lag02 | region), data = d.scaled, REML = FALSE)
cand.set[[147]] <- lmer(prey ~ predator.lag10 + environment.lag03 + (predator.lag10 + environment.lag03 | region), data = d.scaled, REML = FALSE)
cand.set[[148]] <- lmer(prey ~ predator.lag10 + environment.lag04 + (predator.lag10 + environment.lag04 | region), data = d.scaled, REML = FALSE)
cand.set[[149]] <- lmer(prey ~ predator.lag10 + environment.lag05 + (predator.lag10 + environment.lag05 | region), data = d.scaled, REML = FALSE)
cand.set[[150]] <- lmer(prey ~ predator.lag10 + environment.lag06 + (predator.lag10 + environment.lag06 | region), data = d.scaled, REML = FALSE)
cand.set[[151]] <- lmer(prey ~ predator.lag10 + environment.lag07 + (predator.lag10 + environment.lag07 | region), data = d.scaled, REML = FALSE)
cand.set[[152]] <- lmer(prey ~ predator.lag10 + environment.lag08 + (predator.lag10 + environment.lag08 | region), data = d.scaled, REML = FALSE)
cand.set[[153]] <- lmer(prey ~ predator.lag10 + environment.lag09 + (predator.lag10 + environment.lag09 | region), data = d.scaled, REML = FALSE)
cand.set[[154]] <- lmer(prey ~ predator.lag10 + environment.lag10 + (predator.lag10 + environment.lag10 | region), data = d.scaled, REML = FALSE)
cand.set[[155]] <- lmer(prey ~ predator.lag04 + (predator.lag04 | region), data = d.scaled, REML = FALSE)
cand.set[[156]] <- lmer(prey ~ predator.lag05 + (predator.lag05 | region), data = d.scaled, REML = FALSE)
cand.set[[157]] <- lmer(prey ~ predator.lag06 + (predator.lag06 | region), data = d.scaled, REML = FALSE)
cand.set[[158]] <- lmer(prey ~ predator.lag07 + (predator.lag07 | region), data = d.scaled, REML = FALSE)
cand.set[[159]] <- lmer(prey ~ predator.lag08 + (predator.lag08 | region), data = d.scaled, REML = FALSE)
cand.set[[160]] <- lmer(prey ~ predator.lag09 + (predator.lag09 | region), data = d.scaled, REML = FALSE)
cand.set[[161]] <- lmer(prey ~ predator.lag10 + (predator.lag10 | region), data = d.scaled, REML = FALSE)
cand.set[[162]] <- lmer(prey ~ environment.lag00 + (environment.lag00 | region), data = d.scaled, REML = FALSE)
cand.set[[163]] <- lmer(prey ~ environment.lag01 + (environment.lag01 | region), data = d.scaled, REML = FALSE)
cand.set[[164]] <- lmer(prey ~ environment.lag02 + (environment.lag02 | region), data = d.scaled, REML = FALSE)
cand.set[[165]] <- lmer(prey ~ environment.lag03 + (environment.lag03 | region), data = d.scaled, REML = FALSE)
cand.set[[166]] <- lmer(prey ~ environment.lag04 + (environment.lag04 | region), data = d.scaled, REML = FALSE)
cand.set[[167]] <- lmer(prey ~ environment.lag05 + (environment.lag05 | region), data = d.scaled, REML = FALSE)
cand.set[[168]] <- lmer(prey ~ environment.lag06 + (environment.lag06 | region), data = d.scaled, REML = FALSE)
cand.set[[169]] <- lmer(prey ~ environment.lag07 + (environment.lag07 | region), data = d.scaled, REML = FALSE)
cand.set[[170]] <- lmer(prey ~ environment.lag08 + (environment.lag08 | region), data = d.scaled, REML = FALSE)
cand.set[[171]] <- lmer(prey ~ environment.lag09 + (environment.lag09 | region), data = d.scaled, REML = FALSE)
cand.set[[172]] <- lmer(prey ~ environment.lag10 + (environment.lag10 | region), data = d.scaled, REML = FALSE)
